services:
  backend:
    build:
      context: ./app-back-goj
    ports:
      - "4040:4040"
    environment:
      - MONGO_URI=mongodb://mongo:27017/GOJ_Development
      - PORT = 4040
      - UPDATE_DB_WITH_TEST_DATA=TRUE
    depends_on:
      - mongo
    volumes:
      - ./app-back-goj:/usr/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./app-front-ui-goj
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./app-front-ui-goj:/usr/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    logging:
      driver: "none"
    command: mongod --quiet --logpath /dev/null 
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo-data: